version: '3.4'

services:
  doginfo.webapi:
    image: ${DOCKER_REGISTRY-}doginfowebapi
    container_name: doginfowebapi
    hostname: doginfowebapi
    build:
      context: .
      dockerfile: src/DogInfo.WebApi/Dockerfile
    networks:
      - doginfowebapi-network
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    hostname: redis
    command: redis-server
    restart: always
    volumes:
      - ./data:/data
    ports:
      - '6379:6379'
    networks:
      - doginfowebapi-network

networks:
  doginfowebapi-network:
    driver: bridge